name: 'Bounce Hair Boutique '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31443
title: '#getbouncy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#61bfb8'
    - '#c3d854'
    - '#121212'
    - '#c73060'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
